# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import house.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_houseinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=house.models.upload_location),
        ),
    ]
